"""
rag_qa_evaluator.py
===================
Evaluate a RAG pipeline against a gold-standard question set (gt_qa.json).

Key design principle
--------------------
Only the question_id + question text are read from gt_qa.json.
Every other field (answer, required_documents, required_doc_types,
required_political_perspectives, minimum_hops) is intentionally ignored
during retrieval and generation so the RAG must discover the evidence
independently.  Those gold-standard fields are written to the output
only for later evaluation/comparison — they are never injected into
the retrieval or prompt.

Pipeline
--------
1.  Load gt_qa.json  →  extract (question_id, event_id, question) only
2.  Load all chunk JSONs from data/mdkey_chunks/  →  build neighbour index
3.  Connect to the existing persistent ChromaDB
4.  For every question:
      a. Embed query  (e5-mistral asymmetric prefix — FLAW 1)
      b. Retrieve top-k chunks WITHOUT any metadata pre-filter
         so that cross-document / cross-perspective questions can be
         answered properly  (removing the old FLAW 2 over-filtering)
      c. Adaptive k based on question complexity  (FLAW 3)
      d. Deduplicate retrieved chunks by chunk_id  (FLAW 4)
      e. Trim each passage to token budget  (FLAW 5)
      f. Inject left/right neighbours  (FLAW 6)
      g. Derive answered_documents from chunk metadata — NOT from gt_qa
      h. Generate answer with configurable LLM  (FLAW 7 / annotator != retriever)
5.  Save to data/rag_qa_output.json

Output record schema
--------------------
{
  "question_id":                    str,   ← from gt_qa
  "event_id":                       str,   ← from gt_qa
  "question":                       str,   ← from gt_qa
  "rag_answer":                     str,   ← generated by RAG
  "answered_documents":             list,  ← source filenames of retrieved chunks
  "answered_doc_types":             list,  ← doc_type of retrieved chunks
  "answered_political_perspectives":list,  ← perspective of retrieved chunks
  "retrieved_chunk_ids":            list,  ← chunk_ids in retrieval order
  "retrieval_distances":            list,  ← cosine distances
  "qa_model":                       str,
  "qa_provider":                    str,
  "embed_model":                    str,
  --- below only for evaluation convenience, copied verbatim from gt_qa ---
  "gt_answer":                      str,
  "gt_required_documents":          list,
  "gt_required_doc_types":          list,
  "gt_required_political_perspectives": list,
  "gt_minimum_hops":                int,
  "question_type":                  str,
  "reasoning_type":                 str
}

.env keys (same format as news_pipeline.py + rag_qa_generator.py)
------------------------------------------------------------------
CHATAI_API_KEY=...
CHATAI_BASE_URL=https://chat-ai.academiccloud.de/v1
CHATAI_LLM_MODEL=meta-llama-3.1-70b-instruct
CHATAI_EMBED_MODEL=e5-mistral-7b-instruct

QA_LLM_PROVIDER=chatai          # or: anthropic
QA_LLM_MODEL=meta-llama-3.1-70b-instruct
ANTHROPIC_API_KEY=...            # only needed if QA_LLM_PROVIDER=anthropic
"""

import os
import re
import json
import time
import argparse
from pathlib import Path
from typing import Optional

from dotenv import load_dotenv

load_dotenv()

# ---------------------------------------------------------------------------
# Paths
# ---------------------------------------------------------------------------
DATA_DIR          = "data"
CHUNKS_DIR        = os.path.join(DATA_DIR, "mdkey_chunks")
CHROMA_DIR        = os.path.join(DATA_DIR, "chroma_db")
GT_QA_PATH        = os.path.join(DATA_DIR, "gt_qa.json")
OUTPUT_PATH       = os.path.join(DATA_DIR, "rag_qa_output.json")
CHROMA_COLLECTION = "political_news"

# ---------------------------------------------------------------------------
# API / model settings
# ---------------------------------------------------------------------------
CHATAI_BASE_URL   = os.getenv("CHATAI_BASE_URL",    "https://chat-ai.academiccloud.de/v1")
CHATAI_API_KEY    = os.getenv("CHATAI_API_KEY",     "")
CHATAI_LLM_MODEL  = os.getenv("CHATAI_LLM_MODEL",  "meta-llama-3.1-70b-instruct")
CHATAI_EMB_MODEL  = os.getenv("CHATAI_EMBED_MODEL", "e5-mistral-7b-instruct")

QA_LLM_PROVIDER   = os.getenv("QA_LLM_PROVIDER",   "chatai")   # chatai | anthropic
QA_LLM_MODEL      = os.getenv("QA_LLM_MODEL",       CHATAI_LLM_MODEL)
ANTHROPIC_API_KEY = os.getenv("ANTHROPIC_API_KEY",  "")

# ---------------------------------------------------------------------------
# Retrieval knobs
# ---------------------------------------------------------------------------
TOP_K_SIMPLE       = 5    # single-hop / factual
TOP_K_COMPLEX      = 10   # multi-hop / analytical / comparative
MAX_PASSAGE_TOKENS = 350  # ~1 400 chars per retrieved passage
MAX_CONTEXT_CHUNKS = 8    # passages sent to LLM (after neighbour injection)

# ---------------------------------------------------------------------------
# Complexity heuristic
# ---------------------------------------------------------------------------
_COMPLEX_RE = re.compile(
    r"\b(compar|contrast|differ|both|all|across|between|relation|impact|"
    r"analyz|evaluat|assess|why|how does|to what extent|explain|discuss|"
    r"concern|multiple|various|several|throughout)\b",
    re.I,
)

def _is_complex(question: str) -> bool:
    return bool(_COMPLEX_RE.search(question))

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------
def _trim(text: str, max_tokens: int) -> str:
    """Rough token-budget trimmer (1 token ≈ 4 chars)."""
    limit = max_tokens * 4
    return text[:limit] + ("…" if len(text) > limit else "")


def _dedupe_preserve_order(seq: list) -> list:
    seen, out = set(), []
    for x in seq:
        if x not in seen:
            seen.add(x)
            out.append(x)
    return out


# ===========================================================================
# STEP 1 — Load gt_qa.json  (questions only — no answers, no required docs)
# ===========================================================================

def load_gt_questions(gt_path: str) -> list[dict]:
    """
    Read gt_qa.json.  Returns a list of dicts containing ONLY the fields
    needed to drive retrieval.  Gold-standard fields are preserved in a
    separate '_gt' namespace so they can be written to the output for
    evaluation — but are never passed to the retriever or the LLM.
    """
    with open(gt_path, encoding="utf-8") as fh:
        raw = json.load(fh)

    # Accept both a bare list and {"questions": [...]}
    if isinstance(raw, dict):
        raw = raw.get("questions", list(raw.values()))

    records = []
    for item in raw:
        if not isinstance(item, dict):
            continue
        question = item.get("question", "").strip()
        if not question:
            continue
        records.append({
            # ── fields used by the RAG ──────────────────────────────────────
            "question_id":  item.get("question_id", ""),
            "event_id":     item.get("event_id", "unknown"),
            "question":     question,
            # ── gold-standard fields stored for later evaluation only ───────
            "_gt_answer":                          item.get("answer", ""),
            "_gt_required_documents":              item.get("required_documents", []),
            "_gt_required_doc_types":              item.get("required_doc_types", []),
            "_gt_required_political_perspectives": item.get("required_political_perspectives", []),
            "_gt_minimum_hops":                    item.get("minimun_hops", item.get("minimum_hops", 1)),
            "_gt_question_type":                   item.get("question_type", ""),
            "_gt_reasoning_type":                  item.get("reasoning_type", ""),
        })

    print(f"[gt_qa] {len(records)} questions loaded from {gt_path!r}")
    return records


# ===========================================================================
# STEP 2 — Load chunk JSONs for neighbour-injection index
# ===========================================================================

def load_chunk_index(chunks_dir: str) -> dict[str, dict]:
    """
    Build a chunk_id → chunk dict from all JSONs in mdkey_chunks/.
    Used exclusively for neighbour injection (FLAW 6).
    """
    chunk_index: dict[str, dict] = {}
    json_files = sorted(Path(chunks_dir).glob("*.json"))
    if not json_files:
        print(f"  [WARN] No JSON files found in {chunks_dir!r} — neighbour injection disabled")
        return chunk_index

    total = 0
    for jf in json_files:
        with open(jf, encoding="utf-8") as fh:
            data = json.load(fh)

        raw_chunks = data if isinstance(data, list) else data.get("chunks", [])

        stem  = jf.stem
        parts = stem.split("__")
        ev    = parts[0] if len(parts) > 0 else "unknown"
        persp = parts[1] if len(parts) > 1 else "unknown"
        dtype = parts[2] if len(parts) > 2 else "unknown"

        for c in raw_chunks:
            c.setdefault("source",                jf.name)
            c.setdefault("event_id",              ev)
            c.setdefault("political_perspective",  persp)
            c.setdefault("doc_type",              dtype)
            cid = c.get("chunk_id")
            if cid:
                chunk_index[cid] = c
                total += 1

    print(f"[chunks] {len(json_files)} file(s) → {total} chunks indexed for neighbour lookup")
    return chunk_index


# ===========================================================================
# STEP 3 — ChromaDB connection
# ===========================================================================

def get_chroma_collection():
    import chromadb
    from chromadb.utils.embedding_functions import OpenAIEmbeddingFunction

    ef = OpenAIEmbeddingFunction(
        api_base   = CHATAI_BASE_URL,
        api_key    = CHATAI_API_KEY,
        model_name = CHATAI_EMB_MODEL,
    )
    client = chromadb.PersistentClient(path=CHROMA_DIR)
    col = client.get_or_create_collection(
        name               = CHROMA_COLLECTION,
        embedding_function = ef,
    )
    return col


# ===========================================================================
# STEP 4a — Retrieval  (all RAG flaws mitigated)
# ===========================================================================

def retrieve_context(
    question:    str,
    event_id:    str,
    chunk_index: dict[str, dict],
    collection,
) -> list[dict]:
    """
    Returns a list of context dicts ready for the prompt.

    FLAW 1  – e5-mistral asymmetric query prefix
    FLAW 3  – adaptive top-k
    FLAW 4  – dedup by chunk_id
    FLAW 5  – passage trimming
    FLAW 6  – neighbour injection
    NOTE    – FLAW 2 (event_id filter) is intentionally removed here.
              gt_qa questions often span multiple documents / perspectives,
              so we must NOT pre-filter to a single event; the LLM must
              synthesise across the full retrieved set.
    """
    top_k = TOP_K_COMPLEX if _is_complex(question) else TOP_K_SIMPLE

    # FLAW 1: asymmetric query prefix required by e5-mistral
    rich_query = f"query: {question}"

    try:
        result = collection.query(
            query_texts = [rich_query],
            n_results   = top_k,
            include     = ["documents", "metadatas", "distances"],
        )
    except Exception as exc:
        print(f"  [WARN] ChromaDB query error: {exc}")
        return []

    metadatas = result.get("metadatas", [[]])[0]
    documents = result.get("documents", [[]])[0]
    distances = result.get("distances", [[]])[0]

    retrieved: list[dict] = []
    seen_ids:  set[str]   = set()

    for meta, doc, dist in zip(metadatas, documents, distances):
        cid = meta.get("chunk_id", "")

        # FLAW 4: deduplicate
        if cid and cid in seen_ids:
            continue
        if cid:
            seen_ids.add(cid)

        # FLAW 5: trim passage
        passage = _trim(doc, MAX_PASSAGE_TOKENS)

        retrieved.append({
            "chunk_id":              cid,
            "source":                meta.get("source", ""),
            "title":                 meta.get("title", ""),
            "event_id":              meta.get("event_id", event_id),
            "political_perspective": meta.get("political_perspective", ""),
            "doc_type":              meta.get("doc_type", ""),
            "distance":              round(float(dist), 5),
            "text":                  passage,
            "_is_neighbour":         False,
        })

        # FLAW 6: inject left / right neighbours from in-memory index
        for nb_key in ("previous_chunk_id", "next_chunk_id"):
            nb_id = meta.get(nb_key, "")
            if nb_id and nb_id not in seen_ids and nb_id in chunk_index:
                seen_ids.add(nb_id)
                nb = chunk_index[nb_id]
                retrieved.append({
                    "chunk_id":              nb_id,
                    "source":                nb.get("source", ""),
                    "title":                 nb.get("title", ""),
                    "event_id":              nb.get("event_id", event_id),
                    "political_perspective":  nb.get("political_perspective", ""),
                    "doc_type":              nb.get("doc_type", ""),
                    "distance":              round(float(dist) + 0.0001, 5),
                    "text":                  _trim(nb.get("text", ""), MAX_PASSAGE_TOKENS),
                    "_is_neighbour":         True,
                })

    # Cap total to avoid context-window overflow
    retrieved = retrieved[:MAX_CONTEXT_CHUNKS]
    return retrieved


# ===========================================================================
# STEP 4b — Prompt construction
# ===========================================================================

def _build_prompt(question: str, context_chunks: list[dict]) -> str:
    """
    Build the LLM prompt from retrieved passages only.
    No gold-standard fields are ever passed here.
    """
    lines = [
        "You are a factual news Q&A assistant.",
        "Answer the question using ONLY the evidence passages provided below.",
        "If the passages do not contain sufficient information, respond with: 'Insufficient context'.",
        "Be concise (2-5 sentences). Cite passage numbers [1], [2], … where helpful.",
        "",
        f"Question: {question}",
        "",
        "=== Evidence Passages ===",
    ]

    if not context_chunks:
        lines.append("[No passages retrieved]")
    else:
        for i, c in enumerate(context_chunks, 1):
            neighbour_tag = " (context neighbour)" if c.get("_is_neighbour") else ""
            header = (
                f"[{i}] Source: {c.get('source', 'unknown')} | "
                f"Event: {c.get('event_id', '')} | "
                f"{c.get('doc_type', '')} | "
                f"{c.get('political_perspective', '')} | "
                f"dist={c.get('distance', '')}{neighbour_tag}"
            )
            lines.append(header)
            lines.append(c.get("title", ""))
            lines.append(c.get("text", ""))
            lines.append("")

    lines.append("=== Your Answer ===")
    return "\n".join(lines)


# ===========================================================================
# STEP 4c — LLM answer generation
# ===========================================================================

def _call_chatai(prompt: str) -> str:
    from openai import OpenAI
    client = OpenAI(base_url=CHATAI_BASE_URL, api_key=CHATAI_API_KEY)
    resp = client.chat.completions.create(
        model       = QA_LLM_MODEL,
        messages    = [{"role": "user", "content": prompt}],
        max_tokens  = 512,
        temperature = 0.1,
    )
    return resp.choices[0].message.content.strip()


def _call_anthropic(prompt: str) -> str:
    import anthropic
    client = anthropic.Anthropic(api_key=ANTHROPIC_API_KEY)
    resp = client.messages.create(
        model      = QA_LLM_MODEL,
        max_tokens = 512,
        messages   = [{"role": "user", "content": prompt}],
    )
    return resp.content[0].text.strip()


def generate_answer(prompt: str) -> str:
    if QA_LLM_PROVIDER.lower() == "anthropic":
        return _call_anthropic(prompt)
    return _call_chatai(prompt)


# ===========================================================================
# STEP 5 — Derive document-level metadata from retrieved chunks
# ===========================================================================

def derive_answered_metadata(context_chunks: list[dict]) -> tuple[list, list, list]:
    """
    Extract the unique source filenames, doc_types, and political perspectives
    from the retrieved chunks.  These are the RAG's own claimed provenance —
    not the gold standard — for evaluation against gt_qa fields.
    """
    docs  = _dedupe_preserve_order([c["source"] for c in context_chunks if c.get("source")])
    types = _dedupe_preserve_order([c["doc_type"] for c in context_chunks if c.get("doc_type")])
    persp = _dedupe_preserve_order([c["political_perspective"] for c in context_chunks if c.get("political_perspective")])
    return docs, types, persp


# ===========================================================================
# STEP 6 — Full pipeline
# ===========================================================================

def run(
    gt_path:     str          = GT_QA_PATH,
    chunks_dir:  str          = CHUNKS_DIR,
    output_path: str          = OUTPUT_PATH,
    dry_run:     bool         = False,
    limit:       Optional[int]= None,
):
    print(f"\n{'='*68}")
    print(f"  RAG Q&A Evaluator")
    print(f"  Gold-standard QA : {gt_path}")
    print(f"  Chunks dir       : {chunks_dir}")
    print(f"  ChromaDB         : {CHROMA_DIR}")
    print(f"  QA provider      : {QA_LLM_PROVIDER}  model={QA_LLM_MODEL}")
    print(f"  Embed model      : {CHATAI_EMB_MODEL}")
    print(f"  Output           : {output_path}")
    if dry_run:
        print("  *** DRY RUN — no LLM calls ***")
    print(f"{'='*68}\n")

    # 1. Load questions from gt_qa (no answers, no required docs passed to RAG)
    gt_records = load_gt_questions(gt_path)
    if limit:
        gt_records = gt_records[:limit]
        print(f"[limit] processing first {limit} questions\n")

    # 2. Build neighbour index from chunk JSONs
    chunk_index = load_chunk_index(chunks_dir)

    # 3. Connect to ChromaDB
    print("\n[chroma] connecting to persistent collection …")
    collection = get_chroma_collection()
    n_vectors = collection.count()
    print(f"[chroma] '{CHROMA_COLLECTION}' — {n_vectors} vectors\n")

    if n_vectors == 0:
        raise SystemExit(
            "ERROR: ChromaDB collection is empty.\n"
            "Run news_pipeline.py first to index your chunks."
        )

    # 4. Retrieve + generate
    results: list[dict] = []
    total = len(gt_records)

    for idx, rec in enumerate(gt_records, 1):
        question   = rec["question"]
        question_id = rec["question_id"]
        event_id   = rec["event_id"]

        print(f"  [{idx:>3}/{total}] {question_id} | {question[:75]}")

        # Retrieve (FLAW 1, 3-6 mitigated; FLAW 2 intentionally removed)
        context_chunks = retrieve_context(question, event_id, chunk_index, collection)
        print(f"          → {len(context_chunks)} chunks retrieved  "
              f"(neighbours included)")

        # Derive document provenance from retrieved chunks (not from gt_qa)
        answered_docs, answered_types, answered_perspectives = (
            derive_answered_metadata(context_chunks)
        )

        # Generate answer
        if dry_run:
            rag_answer = "[DRY RUN — no LLM call]"
        else:
            prompt = _build_prompt(question, context_chunks)
            try:
                rag_answer = generate_answer(prompt)
            except Exception as exc:
                rag_answer = f"[ERROR: {exc}]"
                print(f"          [WARN] LLM error: {exc}")
            time.sleep(0.25)   # polite rate-limit buffer

        # Build output record
        results.append({
            # ── RAG inputs ──────────────────────────────────────────────────
            "question_id":                      question_id,
            "event_id":                         event_id,
            "question":                         question,
            # ── RAG outputs ─────────────────────────────────────────────────
            "rag_answer":                       rag_answer,
            "answered_documents":               answered_docs,
            "answered_doc_types":               answered_types,
            "answered_political_perspectives":  answered_perspectives,
            "retrieved_chunk_ids":              [c["chunk_id"] for c in context_chunks],
            "retrieval_distances":              [c["distance"]  for c in context_chunks],
            "qa_model":                         QA_LLM_MODEL,
            "qa_provider":                      QA_LLM_PROVIDER,
            "embed_model":                      CHATAI_EMB_MODEL,
            # ── Gold-standard fields (for evaluation only — never fed to RAG) ──
            "gt_answer":                        rec["_gt_answer"],
            "gt_required_documents":            rec["_gt_required_documents"],
            "gt_required_doc_types":            rec["_gt_required_doc_types"],
            "gt_required_political_perspectives": rec["_gt_required_political_perspectives"],
            "gt_minimum_hops":                  rec["_gt_minimum_hops"],
            "question_type":                    rec["_gt_question_type"],
            "reasoning_type":                   rec["_gt_reasoning_type"],
        })

    # 5. Save
    os.makedirs(os.path.dirname(output_path) or ".", exist_ok=True)
    with open(output_path, "w", encoding="utf-8") as fh:
        json.dump(results, fh, ensure_ascii=False, indent=2)

    print(f"\n{'='*68}")
    print(f"  Saved {len(results)} records  →  {output_path}")
    print(f"{'='*68}\n")
    return results


# ===========================================================================
# CLI
# ===========================================================================
if __name__ == "__main__":
    ap = argparse.ArgumentParser(
        description="Evaluate a RAG pipeline against gt_qa.json questions.",
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
    )
    ap.add_argument("--gt",          default=GT_QA_PATH,  help="Path to gt_qa.json")
    ap.add_argument("--chunks-dir",  default=CHUNKS_DIR,  help="Folder with chunk JSONs")
    ap.add_argument("--output",      default=OUTPUT_PATH, help="Output JSON path")
    ap.add_argument("--limit",       type=int, default=None,
                    help="Process only the first N questions (for smoke-testing)")
    ap.add_argument("--dry-run",     action="store_true",
                    help="Run retrieval but skip LLM calls")
    args = ap.parse_args()

    # Guard rails
    if not CHATAI_API_KEY:
        raise SystemExit(
            "ERROR: CHATAI_API_KEY is not set.\n"
            "Add it to your .env:  CHATAI_API_KEY=<your key>"
        )
    if QA_LLM_PROVIDER.lower() == "anthropic" and not ANTHROPIC_API_KEY:
        raise SystemExit(
            "ERROR: QA_LLM_PROVIDER=anthropic but ANTHROPIC_API_KEY is not set."
        )

    run(
        gt_path     = args.gt,
        chunks_dir  = args.chunks_dir,
        output_path = args.output,
        dry_run     = args.dry_run,
        limit       = args.limit,
    )
